import Contatos from '@assets/contatos.svg'
import EscudoIncon from '@assets/Escudoincon.svg'
import Facebook from '@assets/Facebook.svg'
import GeoLocalizacao from '@assets/geolocalizacao.png'
import GoogleIcon from '@assets/googleicon.svg'
import Home from '@assets/Home.svg'
import InsigniaGCM from '@assets/insigniaGcm.svg'
import Instagram from '@assets/Instagram.svg'
import Logo2 from '@assets/Logo2.png'
import Nao from '@assets/Nao.svg'
import Original from '@assets/Original.png'
import Page404Maria from '@assets/page404maria.svg'
import Simbolo from '@assets/simbolo.png'
import Sirene from '@assets/sirene.svg'
import Site from '@assets/Site.svg'
import Support from '@assets/support.svg'
import TopFundoCelular from '@assets/topFundoCelular.svg'
import Voltar from '@assets/voltar.svg'
import Wtt from '@assets/wtt.svg'

export { Contatos, EscudoIncon, Facebook, GeoLocalizacao, GoogleIcon, Home, InsigniaGCM, Instagram, Logo2, Nao, Original, Page404Maria, Simbolo, Sirene, Site, Support, TopFundoCelular, Voltar, Wtt}